config/routes.rb
Rails.application.routes.draw do
  resources :events, only: %i[new create show]
  resources :sessions, only: %i[new create destroy]
  resources :users, only: %i[new create show]
  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'register_event', to: 'events#register_event'
  get 'my_events', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations

  validates :description, presence: true, length: { minimum: 3, maximum: 300 }
  validates :title, presence: true, length: { minimum: 3, maximum: 25 }
  validates :location, presence: true, length: { minimum: 3, maximum: 25 }
  validates :date, presence: true

  scope :upcoming_events, -> { where('date >= ?', Time.zone.now) }
  scope :previous_events, -> { where('date < ?', Time.zone.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :username, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :sign_in?, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def sign_in?
    !(current_user.nil? || (current_user == false))
  end

  def require_user
    return if sign_in?

    flash[:alert] = 'You must be logged in to perform that action'
    redirect_to login_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show register_event edit update destroy]
  before_action :require_user, only: %i[register_event new edit]

  def index
    @events = Event.all
    @previous_events = @events.previous_events
    @upcoming_events = @events.upcoming_events
  end

  def register_event
    if @event.attendees << @current_user
      redirect_to root_path, notice: 'Registered for the event successfully.'
    else
      redirect_to root_path, alert: 'Unable to Register for the event.'
    end
  end

  def show
    @users = @event.attendees
    return unless sign_in?

    @not_registered = true if @users.where(id: @current_user.id)[0].nil?
  end

  def new
    @event = Event.new
  end

  def edit
    redirect_to root_path if current_user.id != @event.creator_id
  end

  def create
    redirect_to login_path if session[:user_id].nil?
    @current_user = User.find(session[:user_id])
    @event = @current_user.events.build(event_params)
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
      render :show, status: :ok, location: @event
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
    head :no_content
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :date, :location)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    return unless sign_in?

    flash[:notice] = 'User logged already'
    redirect_to root_path
  end

  def create
    @user = User.find_by(email: (params[:session][:email]))
    if !@user.nil?
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome! Successful logged in'
      redirect_to root_path
    else
      flash.now[:alert] = 'Worng or nonexistent Email'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Goodbye! Successful logged out '
  end

  private

  def session_params
    params.permit(:email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: %i[show edit update destroy]

  def show
    @created_events = @current_user.events
    @attend_events = @current_user.attended_events
    @upcoming_events = @attend_events.upcoming_events
    @prev_events = @attend_events.previous_events
    @events = Event.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'User was successfully created and logged in'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Log in the ginven user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_eventslist.html.erb
<div class="container">
  <div class="row">
    <div class="[ col-xs-12 col-sm-offset-10 col-sm-8 ]">
      <ul class="event-list">
        <% @events.each do |event|%>
          <li>
            <time datetime= <% event.date %>>
              <span class="day"><%= event.date.day %></span>
              <span class="month"><%= event.date.strftime("%B")[0...3] %></span>
              <span class="year"><%= event.date.year %></span>
            </time>
            <img alt="Independence Day" src="https://farm4.staticflickr.com/3100/2693171833_3545fb852c_q.jpg" />
            <div class="info">
              <h2 class="title"><%= event.title %></h2>
              <p class="desc"><%= event.description%></p>
              <small class="ml-2 badge badge-secondary">Attendees: <%= event.attendee_ids.count %></small><br>
              <%= link_to 'Show Event', event_path(event), class:"btn btn-success ml-2"%>
            </div>
            <div class="social">
              <ul>
                <li class="facebook" style="width:33%;"><a href="#facebook"><span class="fa fa-facebook"></span></a></li>
                <li class="twitter" style="width:34%;"><a href="#twitter"><span class="fa fa-twitter"></span></a></li>
                <li class="google-plus" style="width:33%;"><a href="#google-plus"><span class="fa fa-google-plus"></span></a></li>
              </ul>
            </div>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</div>

app/views/application/_newevent.html.erb
 <%= form_with(model: @event, local: true) do |form| %>
  <% if @event.errors.any? %>
    <div>
      <h2><%= pluralize(@event.errors.count, "error") %> prevented this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-10 col-sm-offset-10 col-md-offset-4 mx-auto">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Create a new event</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
              <div class="form-group">
              <%= form.label :title %>
              <%= form.text_field :title, placeholder: "Event Title", class:"form-control input-sm" %>
              </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
              <div class="form-group">
                <%= form.label :location%>
                <%= form.text_field :location, placeholder: "Where?", class:"form-control input-sm"%>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
              <div class="form-group">
                <%= form.label :date, "When?" %>
                <br>
                <%= form.date_field :date %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, placeholder: "Description", class:"form-control input-sm"%>
          </div>

          
          <%= form.submit%>
          <%end%>
        </div>
      </div>
    </div>
  </div>

app/views/application/_previousevents.html.erb
<div class="container">
  <div class="row">
    <div class="[ col-xs-12 col-sm-offset-10 col-sm-8 ]">
      <ul class="event-list">
        <% @events.previous_events.each do |event| %>
          <li>
            <time datetime= <% event.date %>>
              <span class="day"><%= event.date.day %></span>
              <span class="month"><%= event.date.strftime("%B")[0...3] %></span>
              <span class="year"><%= event.date.year %></span>
            </time>
            <img alt="Independence Day" src="https://farm4.staticflickr.com/3100/2693171833_3545fb852c_q.jpg" />
            <div class="info">
              <h2 class="title"><%= event.title %></h2>
              <p class="desc"><%= event.description %></p>
              <small class="ml-2 badge badge-secondary">Attendees: <%= event.attendee_ids.count %></small><br>
              <%= link_to 'Show Event', event_path(event), class:"btn btn-success ml-2"%>
            </div>
            <div class="social">
              <ul>
                <li class="facebook" style="width:33%;"><a href="#facebook"><span class="fa fa-facebook"></span></a></li>
                <li class="twitter" style="width:34%;"><a href="#twitter"><span class="fa fa-twitter"></span></a></li>
                <li class="google-plus" style="width:33%;"><a href="#google-plus"><span class="fa fa-google-plus"></span></a></li>
              </ul>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/application/_upcomingevents.html.erb
<div class="container">
  <div class="row">
    <div class="[ col-xs-12 col-sm-offset-10 col-sm-8 ]">
      <ul class="event-list">
        <% @events.upcoming_events.each do |event| %>
          <li>
            <time datetime= <% event.date %>>
              <span class="day"><%= event.date.day %></span>
              <span class="month"><%= event.date.strftime("%B")[0...3] %></span>
              <span class="year"><%= event.date.year %></span>
            </time>
            <img alt="Independence Day" src="https://farm4.staticflickr.com/3100/2693171833_3545fb852c_q.jpg" />
            <div class="info">
              <h2 class="title"><%= event.title %></h2>
              <p class="desc"><%= event.description %></p>
              <small class="ml-2 badge badge-secondary">Attendees: <%= event.attendee_ids.count %></small><br>
              <%= link_to 'Show Event', event_path(event), class:"btn btn-success ml-2"%>
            </div>
            <div class="social">
              <ul>
                <li class="facebook" style="width:33%;"><a href="#facebook"><span class="fa fa-facebook"></span></a></li>
                <li class="twitter" style="width:34%;"><a href="#twitter"><span class="fa fa-twitter"></span></a></li>
                <li class="google-plus" style="width:33%;"><a href="#google-plus"><span class="fa fa-google-plus"></span></a></li>
              </ul>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<h2>Listing all Events: </h1>

<p>
<%= link_to 'Create new event', new_event_path %>
</p>
<div>
   <button class="btn btn-primary" >
      Events <span class="badge badge-light"><%= @events.all.count%></span>
  </button>
  <button class="btn btn-danger">
    Upcoming Events <span class="badge badge-light"> <%= @events.upcoming_events.count %>
    </span>
  </button>
  <button class="btn btn-warning">
    Previous Events <span class="badge badge-light"><%= @events.previous_events.count %></span> 
  </button>
</div>
<hr>
<h2>Upcoming events</h2> 
<%= render 'upcomingevents'%>
<hr>
<h2>Previous events</h2>
<%= render 'previousevents'%>
<hr>
<h2>All events:</h2>
<%= render 'eventslist' %>

app/views/events/new.html.erb
 <%= render 'newevent'%>

app/views/events/show.html.erb

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.date %>
</p>

  <% if @not_registered and current_user %>
    <h3>
    <a href=<%= register_event_path(id: params[:id]) %> role="button">Register Now</a> 
    </h3>
  <% elsif current_user %>
    <h4>
    You already Registered for this event
    </h4>
  <% end %>

<h2> Event Attendees (<%= @event.attendee_ids.count%>) </h2>

<ul>
  <% @users.each do |user| %>
   <li> <%= user.username %> </li>  
  <% end %> 
</ul>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar d-flex justify-content-end px-4">
        <% if current_user %>
        <a href= <%= root_path %> class="btn btn-primary"> Home </a>
          <strong > <a href=  <%= my_events_path %> class="btn btn-primary mx-2" > Dashboard: <%= current_user.username %> </a> </strong>
          <a href=  <%= logout_path %> class="btn btn-secondary"> Sign out </a>
        <% else %>
          <% if !current_page?(root_path)%>
            <a href= <%= root_path %> class="btn btn-primary"> Home </a>
          <% else %>
            <a href= <%= login_path %> class="btn btn-primary mr-2"> Login </a>
            <a href= <%= new_user_path%>  class="btn btn-secondary"> Sign Up </a>
          <% end %>
        <% end %>
    </nav>
  </header>

    <% flash.each do |key , msg|%>
      <% if key === 'notice' %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% elsif key === 'alert' %>
      <div class="alert alert-danger alert-dismissible fade show w-50 mx-auto" role="alert">
        <strong> <%= msg %> </strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>
    <% end %>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/create.html.erb
  <div id="form" class="sidenav">
          <div class="login-main-text">
              <h2>Private Events<br> Login Page</h2>
              <p>Login or register from here to access.</p>
          </div>
  </div>
        <div class="main">
         <div class="col-md-8 col-sm-12">
            <div class="login-form">
              <%= form_for @user do |f| %>
                  <div class="form-group">
                  <%= f.label :username, "Username" %>
                  <%= f.text_field :username, id: 'username', class:"form-control", placeholder:"User Name" %>
                  </div>
                  <div class="form-group">
                    <%= f.label :email, "Email" %>
                    <%= f.text_field :email, id: 'user_email', class:"form-control" , placeholder:"email" %> 
                  </div>
                  <%= f.submit "Register", class:"btn btn-secondary" %>
                  <%= link_to 'Log in', login_path , class:"btn btn-primary"%>
                  <% end %>
            </div>
         </div>
      </div>
      

app/views/users/new.html.erb
  <div id="form" class="sidenav">
          <div class="login-main-text">
              <h2>Private Events<br> Login Page</h2>
              <p>Login or register from here to access.</p>
          </div>
  </div>
        <div class="main">
         <div class="col-md-8 col-sm-12">
            <div class="login-form">
              <%= form_for @user do |f| %>
                <% if @user.errors.any? %>
                  <div>
                    <h4><%= pluralize(@user.errors.count, "error(s)") %> prevented this user from being created:</h4>

                    <ul>
                      <% @user.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                  <div class="form-group">
                  <%= f.label :username, "Username" %>
                  <%= f.text_field :username, id: 'username', class:"form-control", placeholder:"User Name" %>
                  </div>
                  <div class="form-group">
                    <%= f.label :email, "Email" %>
                    <%= f.text_field :email, id: 'user_email', class:"form-control" , placeholder:"email" %> 
                  </div>
                  <%= f.submit "Register", class:"btn btn-secondary" %>
                  <%= link_to 'Log in', login_path , class:"btn btn-primary"%>
                  <% end %>
            </div>
         </div>
      </div>
      

app/views/users/show.html.erb
<%= provide(:title, "User-Events") %>
     <hr>
    <div>
      <button class="btn btn-primary" >
        Events <span class="badge badge-light"><%= @events.all.count%></span>
      </button>
     
      <button class="btn btn-success">
        Will show up
        <span class="badge badge-light"> <%= @current_user.attended_event_ids.count %>
        </span>
      </button>

      <button class="btn btn-danger">
        Upcoming Events <span class="badge badge-light"> <%= @events.upcoming_events.count %>
        </span>
      </button>

      <button class="btn btn-warning">
        Previous Events <span class="badge badge-light"><%= @events.previous_events.count %></span> 
      </button>
  </div>
   <hr>
  <h2>Events that you marked as atendee:</h2>
  <div class="container">
      <div class="row">
        <div class="[ col-xs-12 col-sm-offset-10 col-sm-8 ]">
          <ul class="event-list">
            <% @current_user.attended_event_ids.each do |id| %>
              <li>
                <time datetime= <% @events.find(id).date %>>
                  <span class="day"><%= @events.find(id).date.day %></span>
                  <span class="month"><%= @events.find(id).date.strftime("%B")[0...3] %></span>
                  <span class="year"><%= @events.find(id).date.year %></span>
                </time>
                <img alt="Independence Day" src="https://farm4.staticflickr.com/3100/2693171833_3545fb852c_q.jpg" />
                <div class="info">
                  <h2 class="title"><%= @events.find(id).title %></h2>
                  <p class="desc"><%= @events.find(id).description %></p>
                  <small class="ml-2 badge badge-secondary">Attendees: <%= @events.find(id).attendee_ids.count %></small><br>
                  <%= link_to 'Show Event', event_path(id), class:"btn btn-success ml-2"%>
                </div>
                <div class="social">
                  <ul>
                    <li class="facebook" style="width:33%;"><a href="#facebook"><span class="fa fa-facebook"></span></a></li>
                    <li class="twitter" style="width:34%;"><a href="#twitter"><span class="fa fa-twitter"></span></a></li>
                    <li class="google-plus" style="width:33%;"><a href="#google-plus"><span class="fa fa-google-plus"></span></a></li>
                  </ul>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
  </div>
  <hr>